### ISSUE TITLE
Support XTT handshake

### ISSUE THREAD

**Issue by drbild** [xaptum/enftun#1]
Add support for using XTT to provision the identity certificate and key. Currently only preconfigured static certs are supported.

- [x] add configuration section for xtt options, e.g.:
       `xtt.enable` (default `true`)
       `xtt.tcti_type` (default `device` | `socket`)
       `xtt.device` (default `/dev/tpm0`)
       `xtt.socket`
- [x] add `enftun_xtt.{h,c}` files that implement an `enftun_xtt_handshake(...)` function or similar.  See `enftun_tls.{h.c}` and `enftun_tun.{h.c}` for an example layouts.
- [x] integrate the `enftun_xtt_handshake` function into the main `enftun_connect(...)` function.
- [x] support compiling `enftun` without xtt support

## Algorithm for Running XTT and TLS
The configuration file specifies the file names for the certificate and private key files (these can be PEM or DER encoded).  The following logic should be used in `enftun_connect(...)` to regarding these files.

If the files exist, attempt to establish the TLS tunnel.

If the files don't exist or the TLS tunnel fails (due to an invalid certificate/key, not a network error) and XTT is enabled, try to run the XTT handshake.

If the XTT handshake succeeds, save the cert and key to the files and try to connect the TLS tunnel again.

If XTT fails or the second TLS attempt fails, return an error. (The outer `enftun_main` loop will sleep for a second and try the whole `enftun_connect` again.)

## Operating without XTT support

Some systems like backend servers will not use `xtt`, just pre-distributed certificates.  To avoid requiring unnecessary dependencies like xtt, ecdaa, and xaptum-tpm, it should be possible to compile `enftun` without `xtt` support.

Here are two options for implementing this.

### ifdefs

An easy option is to `#ifdef` out the xtt-specific code in `enftun.c` and not compile the `enftun_xtt.c`.  The config parsers should return an error if the "xtt" section is found.

This approach results in ugly code and potentially brittle `ifdef` trees that are hard to reason about.

### abstraction

An alternative is to abstract out the strategy for obtaining the TLS credentials. 

The base strategy used without `xtt` can simply return the cert and key from disk.  The xtt strategy first runs xtt and then returns the cert and key.

The strategies can be implemented as functions and accessed via a function pointer, so that the calling code is not away which strategy it is calling.

This approach could result in cleaner code that is easier to maintain.

The exact API needs to be worked out.

**Comment by drbild** [comment]
@kathrynfejer I've made some big changes to the way the config/options stuff is structured.

You should rebase your work on master soon. There will be some manual effort involved.  If you get stuck, let me know and I can help.

**Comment by kathrynfejer** [comment]
Ok, will do. I rebased about halfway through the day yesterday, but I see lots of changes have been made since then. 

I believe XTT has been integrated, but having issues testing the code with the router.py/the xtt tool as neither does the whole thing.
