### ISSUE TITLE
ENFTun has to define the SCM socket number as a magic number

### ISSUE THREAD

**Issue by dberliner** [xaptum/enftun#107]
User-space apps do not have access to our kernel header files, the sock IDs are defined in the `arm-buildroot-linux-gnueabihf` project (the userspace C libraries for the device). We can overlay our own patch, fork and modify or just keep defining it here for now.

**Comment by drbild** [comment]
`enftun` does have access to our kernel header files.  The firmware for the router card is built against our fork of Linux that has your SCM changes and header files.
