### ISSUE TITLE
Communication through enf0 blocks after an invalid source IP is detected

### ISSUE THREAD

**Issue by peterhaijen** [xaptum/enftun#25]
Scenario: the enftun application detects a packet with an invalid source IP:

`<7>DROP [ egress]: invalid src IP`

This results in further communication through enf0 being blocked.

**Comment by peterhaijen** [comment]
When this happens, it is possible to restart communication (echo request/reply) through enf0, by terminating the link with the server (route.py), which can be done by hitting `Ctrl-C` in the terminal running `route.py`. This will drop the connection with `enftun`, which will immediately re-establish the connection, allowing an ongoing ping request to continue as if nothing happened.

**Comment by drbild** [comment]
The `DROP` behavior is correct, and I've observed that here without a subsequent loss of connectivity.  If it is related to this issue, it's either a new bug or just manifests in certain situations.

**Comment by drbild** [comment]
This was indeed a new bug, introduced by 8d73eba.  The logic was confusing, leading to an incorrect "fix".

This is fixed by #26, which makes the logic explicit.

**Comment by peterhaijen** [comment]
Excellent!
