### ISSUE TITLE
Send Router Advertisements to the host

### ISSUE THREAD

**Issue by drbild** [xaptum/enftun#48]
# Router advertisements

`enftun` configures routes for the ENF by running on `iproute2` commands.  This will not work for the router card, where `enftun` is not running on the host.  `enftun` should instead send IPv6 router advertisements containing these routes.

- [x] Send router advertisement when first connected and periodically thereafter (say 600 seconds).
- [x] Respond to router solicitations with a router advertisement.
- [x] Configure the router card to not accept RAs on `enf0`. Otherwise it will try to interpret the RA itself.

The router advertisements should contain the following:
* Header
  - src IP of fe80::1
  - dst IP of ff02::1
* RA
  - Flags: MANAGED
  - Router Preference: High
  - MTU: 1280
  - Router Default Lifetime: 0 # do not advertise as a default router
* Route Option  - one for each route listed in the `route.prefixes` config
  - Route Lifetime: 3 * period of the RAs
  - Route Preference: High
* ~~Source Link Layer Address (optional, see the "Neighbor Advertisement" section below)~~
  - ~~a MAC address specified in the config (`tun.lladdr`)~~

I think that a `Prefix` option is not needed, since this tunnel is point-to-point (there's no LAN prefix) and we don't support SLAAC.  However, if we want to send it, the following options should be correct:
* Prefix Option
  - Flags: not on-link, not autonomous
  - Valid Lifetime: 30 days

# Neighbor Advertisements

The router card is exposed on the host as an L2 interface, so it needs to learn the MAC address corresponding to the  router IP (`fe80::1`).

Generically, it will issue neighbor solicitations to the router IP (`fe80::`) to determine the MAC address of the router card (`usb0` interface).  The router card would need to respond with a neighbor advertisement.  This would require implementing support for these message types.

### Option 1

However, the router advertisement can itself can contain its own link-layer address. I propose we use this, to avoid the need to support the two neighbor messages.

Most uses of `enftun` are L3 only, so they won't specify a `tun.lladdr` and that option won't be included in the RAs.  For the router card, the MAC address of `usb0` can be hard-coded (passed to the `g_ether` module and in the `enftun` config.)

### Option 2

`enftun` is intentionally L3-only, so having it include a link-layer address is a bit odd. So a different approach to remove link-layer addresses entirely from the `enftun`.  Don't include them in the RA and don't handle NS in `enftun`.

Instead, handle ND with a different service running on the router card, e.g., inside of `xbridge`.  Before passing a packet from `usb0` to `enf0`, check if it is a NS for `fe80::1`.  If so, send a NA to `usb0` instead.

# Implementation

These features should be implemented in a `src/ndp.c` module, which should send an RA when triggered.

### Triggering an RA

Sending a packet is asynchronous, so we separate the concepts of sending vs scheduling an RA. 
Only a single router advertisement should be in flight at a time.

An RA should be scheduled when an RS is received or the periodic timer (a `libuv` timer) expires. This scheduling is idempotent: If an RA is already scheduled, that particular trigger has no effect. Don't schedule multiple RAs out into the future.

If no RA is in-flight, the scheduled RA should be sent immediately.  If an RA is already in-flight, it should be sent after the previous one finishes.

### Sending an RA

The `enftun_packet` struct is a buffer for network packet data (similar to the `sk_buff` in the Linux kernel).  The `enftun_crb` struct is used to schedule a packet for reading or writing (similar to the USB request `urb` in the Linux kernel).    `enftun_crb_write(crb, chan`) will asynchronously write the 
the specified CRB to the specified channel.  The callback attached to the CRB will be called upon completion.

Only a single RA should be in-flight at a time, so the `enftun_ndp` struct can hold a single, statically allocated packet and CRB.  The `enftun_context` struct holds the tunnel channel as a member `tunchan`.

### Intercepting RSs

This module should expose a filter hook that is registered is called in the `enftun.c:chain_egress_filter()` function.  The hook should filter out RSs and schedule the sending of an RA.

### NS and NA

Neighbor discovery can be handled in a similar fashion to RAs and RSs, if "Option 1" above is chosen.

**Comment by peterhaijen** [comment]
Branch `nda` on my fork of the `xaprc` Git project adds code to `xbridge` to assemble and transmit a Neighbor Advertisement packet, which is correctly recognized and parsed by Wireshark running on the host. Needs further tests to make sure that content-wise the packet is OK.

**Comment by drbild** [comment]
Fixed by #60
