### ISSUE TITLE
Add Travis build

### ISSUE THREAD

**Issue by drbild** [xaptum/enftun#49]
Add Travis config to build the main configurations (with and without XTT support) in `Dev`, `Release`, `DevDebug`, and `Debug` types, similar to the XTT Travis config.  The `Dev*` variants should enable `-Werror`.

**Comment by kathrynfejer** [comment]
Was the initial thought to have travis download and install all the dependencies or to run the tests inside a Docker image?

**Comment by drbild** [comment]
Let's have travis install the dependencies from the Xaptum Debian Bintray.  This will test that the required dependencies are actually published --- rather than travis building the dependencies from a possible un-published commit.
