### ISSUE TITLE
Initializing tcp AND psock

### ISSUE THREAD

**Issue by kathrynfejer** [xaptum/enftun#91]
Currently the same code repeats in both `xtt.c` and `tls.c` to initialize the `enftun_tcp_native` and `enftun_tcp_psock` structs. This can be combined into one function.

It would be ideal to be able to initialize either one so that we can support both tcp and psock simultaneously (falling back to the psock connection when tcp is not available). 

Connected to #73

**Comment by drbild** [comment]
Addressed by #108
